server:
  port: 8080

spring:
  application:
    name: campus-work-order-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

captcha:
  expiration: 120s

auth:
  session-expiration: 24h

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
